### ISSUE TITLE
🏖️ [ 6월 3주차 ]

### ISSUE THREAD

**Issue by Bori-github** [Gamangjum-lihou/study-log-archive#5]
🚀 기간 : 23.06.12 - 23.06.18

- 블로그 링크와 관련 태그를 댓글로 남겨주세요.
- 제출 후 Labels에서 각자 이름 라벨 선택해주세요.
- 태그는 여러 개를 지정할 수 있습니다. (최대 3개)

[ 추가 ]
- 6월 3주차, 4주차는 방학입니다.
- 선택적으로 내용 업로드 해주세요.

예시)
블로그 링크 :
태그 :

**Comment by Ryan-Dia** [comment]
블로그 링크 : [왜 기업들은 Yarn Berry를 많이 사용할까? - (1) (feat : NPM)](https://html-jc.tistory.com/676)
태그 : `Node.js`

**Comment by Bori-github** [comment]
블로그 링크 : [next/image 반응형 적용하기 | Next.js 13](https://velog.io/@qhflrnfl4324/nextimage-%EB%B0%98%EC%9D%91%ED%98%95-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0-Next.js-13)
태그 : `next.js`, `css`

**Comment by SWARVY** [comment]
블로그 링크 : [프로젝트를 마무리하면서](https://swarvy.tistory.com/146)
태그 : `React.js`
